name: rabegn
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  firebase_core: 1.16.0
  firebase_auth: 3.3.17
  cloud_firestore: 3.1.14
  firebase_storage: 10.2.15
  get_storage: 2.0.3
  flex_color_scheme: 5.0.1
  glass: 1.0.1+1
  image_picker: 0.8.5+3
  timeago: 3.2.2
  cached_network_image: 3.2.0
  uuid: 3.0.6
  random_string: 2.3.1
  flutter: 
    sdk: flutter
  carousel_slider: ^4.1.1

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Outfit
      fonts: 
        - asset: assets/fonts/Outfit-Regular.ttf
        - asset: assets/fonts/Outfit-Bold.ttf
          weight: 700
  uses-material-design: true

